apiVersion: batch/v1
kind: Job
metadata:
  name: import-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: import
        command:
          - /bin/bash
          - '-c'
          - |
            set -x
            sh /scripts/import.sh
        image: 'quay.io/enterprisedb/postgresql:16.4'
        volumeMounts:
          - mountPath: /scripts
            name: importsql-sh
          - mountPath: /scripts/sql/heroes.sql
            name: heroes-sql
            subPath: heroes.sql
          - mountPath: /scripts/sql/villains.sql
            name: villains-sql
            subPath: villains.sql
      restartPolicy: Never
      volumes:
      - name: importsql-sh
        configMap:
          name: importsql-sh
      - name: heroes-sql
        configMap:
          name: heroes-sql
      - name: villains-sql
        configMap:
          name: villains-sql