apiVersion: v1
stringData:
  password: DevZone2024#
  username: app_user
kind: Secret
metadata:
  name: app-secret-prod
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  password: postgres
  username: postgres
kind: Secret
metadata:
  name: postgres-user
type: kubernetes.io/basic-auth